name: AtlasCoreConnector
version: 1.0.0
main: me.help.minecraft_store.AtlasCoreConnector
api-version: 1.18
# This ensures your plugin loads AFTER the plugins it needs.
depend:
  - PlaceholderAPI
softdepend:
  - AuraSkills
  - Fabled